"""Send email with existing reports."""
import logging
from src.email_client import EmailClient
from config.settings import settings
from pathlib import Path
import sys
sys.path.insert(0, '.')


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def main():
    report_month = "November 2025"
    report_dir = Path("reports/2025-11")

    # Check files exist
    pptx_path = report_dir / "executive_summary.pptx"
    audio_path = Path("reports/audio/executive_summary_2025_11.mp3")

    attachments = []
    if pptx_path.exists():
        attachments.append(str(pptx_path))
        logger.info(f"Found PowerPoint: {pptx_path}")
    else:
        logger.error(f"PowerPoint not found: {pptx_path}")
        return

    if audio_path.exists():
        attachments.append(str(audio_path))
        logger.info(f"Found audio: {audio_path}")

    # Email body
    voice_note = """
    <p><strong>🎧 Audio Summary:</strong> We've included an audio narration of this month's 
    executive summary. Listen to it for a quick overview while on the go!</p>
    """ if audio_path.exists() else ""

    body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #3498db;">📊 Monthly Executive Summary - {report_month}</h2>
        
        <p>Hello,</p>
        
        <p>Please find attached the executive summary report for <strong>{report_month}</strong>.</p>
        
        {voice_note}
        
        <h3>Attached Files:</h3>
        <ul>
            <li><strong>Executive Summary (PowerPoint)</strong> - Comprehensive presentation with AI-generated infographics</li>
            {"<li><strong>Audio Narration (MP3)</strong> - Voice summary of key findings</li>" if audio_path.exists() else ""}
        </ul>
        
        <p>The full detailed reports are available in the reports folder.</p>
        
        <hr style="border: 1px solid #eee; margin: 20px 0;">
        
        <p style="color: #666; font-size: 12px;">
            This is an automated report generated by the Analytics Pipeline.<br>
            For questions, please contact the data team.
        </p>
    </body>
    </html>
    """

    # Send email (audio only - PowerPoint too large)
    logger.info("Sending email with audio attachment only...")
    logger.info(
        f"PowerPoint is {pptx_path.stat().st_size / 1024 / 1024:.1f}MB - too large for email")

    email_client = EmailClient()
    subject = f"📊 Executive Summary Report - {report_month}"

    try:
        email_client.send_email(
            subject=subject,
            body=body,
            attachment_path=[str(audio_path)] if audio_path.exists() else []
        )
        logger.info(f"✓ Email sent successfully to {settings.EMAIL_TO}")
        logger.info(f"  PowerPoint location: {pptx_path}")
    except Exception as e:
        logger.error(f"✗ Failed to send email: {e}")
        raise


if __name__ == "__main__":
    main()
