"""
Monthly Report Generation and Email Script with Voice Narration.

This script:
1. Generates all monthly reports (HTML, charts, PowerPoint)
2. Creates a voice narration of the executive summary using ElevenLabs
3. Sends an email with the PowerPoint and audio file attached

Usage:
    python scripts/send_monthly_report.py                    # Previous month
    python scripts/send_monthly_report.py --month 2025-11    # Specific month
    python scripts/send_monthly_report.py --no-voice         # Skip voice generation
"""
from config.settings import settings
from src.email_client import EmailClient
from src.reporting.report_builder import ReportBuilder
import argparse
import logging
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))


logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def generate_email_body(report_month: str, has_voice: bool) -> str:
    """Generate HTML email body."""
    voice_note = """
    <p><strong>🎧 Audio Summary:</strong> We've included an audio narration of this month's 
    executive summary. Listen to it for a quick overview while on the go!</p>
    """ if has_voice else ""

    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #3498db;">📊 Monthly Executive Summary - {report_month}</h2>
        
        <p>Hello,</p>
        
        <p>Please find attached the executive summary report for <strong>{report_month}</strong>.</p>
        
        {voice_note}
        
        <h3>Attached Files:</h3>
        <ul>
            <li><strong>Executive Summary (PowerPoint)</strong> - Comprehensive presentation with insights and recommendations</li>
            {"<li><strong>Audio Narration (MP3)</strong> - Voice summary of key findings</li>" if has_voice else ""}
        </ul>
        
        <p>The full detailed reports are available in the reports folder.</p>
        
        <hr style="border: 1px solid #eee; margin: 20px 0;">
        
        <p style="color: #666; font-size: 12px;">
            This is an automated report generated by the Analytics Pipeline.<br>
            For questions, please contact the data team.
        </p>
    </body>
    </html>
    """


def main():
    parser = argparse.ArgumentParser(
        description='Generate and send monthly reports with voice narration')
    parser.add_argument(
        '--month', type=str, help='Report month in YYYY-MM format (default: previous month)')
    parser.add_argument('--no-voice', action='store_true',
                        help='Skip voice narration generation')
    parser.add_argument('--no-email', action='store_true',
                        help='Skip sending email')
    args = parser.parse_args()

    try:
        # Step 1: Build reports
        logger.info("=" * 60)
        logger.info("MONTHLY REPORT GENERATION")
        logger.info("=" * 60)

        builder = ReportBuilder(report_month=args.month)
        builder.build_report(include_voice=not args.no_voice)

        report_month = builder.report_month.strftime('%B %Y')
        attachments = []

        # Get PowerPoint path
        pptx_path = builder.output_dir / 'executive_summary.pptx'
        if pptx_path.exists():
            attachments.append(str(pptx_path))
            logger.info(f"PowerPoint ready: {pptx_path}")

        # Get audio path if voice was generated
        audio_path = None
        if not args.no_voice:
            month_slug = builder.report_month.strftime('%Y_%m')
            potential_audio = Path(
                f"reports/audio/executive_summary_{month_slug}.mp3")
            if potential_audio.exists():
                audio_path = str(potential_audio)
                attachments.append(audio_path)
                logger.info(f"Audio ready: {audio_path}")

        # Step 3: Send email (if enabled)
        if not args.no_email and attachments:
            logger.info("-" * 60)
            logger.info("SENDING EMAIL")
            logger.info("-" * 60)

            email_client = EmailClient()
            subject = f"📊 Executive Summary Report - {report_month}"
            body = generate_email_body(
                report_month, has_voice=bool(audio_path))

            email_client.send_email(
                subject=subject,
                body=body,
                attachment_path=attachments
            )

            logger.info(f"Email sent to {settings.EMAIL_TO}")

        logger.info("=" * 60)
        logger.info("COMPLETE")
        logger.info("=" * 60)
        logger.info(f"Reports saved to: {builder.output_dir}")
        if attachments:
            logger.info(f"Attachments: {len(attachments)} files")

    except Exception as e:
        logger.error(f"Error: {e}")
        raise


if __name__ == "__main__":
    main()
